# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      env: # Or as an environment variable
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        ENV_CONFIG: ${{ secrets.ENV_CONFIG }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: ./deploy.sh deploy
